#!/usr/bin/env node
/**
 * Build: TypeScript -> self-contained HTML pages.
 *
 *   src/app.ts            -> dist/pt_frontend.html   (engineering dashboard)
 *   src/patient/main.ts   -> dist/pt_patient.html    (patient chat)
 *
 * Each page is one file with CSS, JS and logo assets inlined, so it has zero
 * external references and works over the Colab proxy, from a static server, and
 * straight off the filesystem.
 *
 *   node build.mjs                    build both pages + the Colab bundle
 *   node build.mjs --no-minify        readable bundle, for debugging
 *   node build.mjs --boot '<json>'    bake a boot config into the pages
 *   node build.mjs --embed-demo 2     bake a demo scenario in as the payload
 *   node build.mjs --page patient     build only one page
 *   node build.mjs --out preview.html emit a one-off page under this name
 */

import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, "src");
const DIST = join(ROOT, "dist");
const ASSETS = join(ROOT, "assets");

const args = process.argv.slice(2);
const flag = (name) => args.includes(name);
const opt = (name, dflt = null) => {
  const i = args.indexOf(name);
  return i >= 0 && args[i + 1] ? args[i + 1] : dflt;
};

const MIME = {
  ".png": "image/png",
  ".svg": "image/svg+xml",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
};

const PAGES = [
  {
    key: "dashboard",
    entry: "src/app.ts",
    css: "src/styles.css",
    out: "pt_frontend.html",
    title: "Pipeline — Hospital Price Transparency | CMU–NIST AIMSEC",
    description:
      "Step-by-step view of the price-transparency pipeline: retrieval, code validation and CMS machine-readable file pricing.",
  },
  {
    key: "patient",
    entry: "src/patient/main.ts",
    css: "src/patient/styles.css",
    out: "pt_patient.html",
    title: "What will this cost? — Hospital Price Transparency | CMU–NIST AIMSEC",
    description:
      "Ask what a procedure might cost. Every figure is linked to the price the hospital is required to publish.",
  },
];

async function dataUri(file) {
  const ext = file.slice(file.lastIndexOf(".")).toLowerCase();
  const buf = await readFile(join(ASSETS, file));
  return `data:${MIME[ext] ?? "application/octet-stream"};base64,${buf.toString("base64")}`;
}

/**
 * The logo files are real downloads from cmu.edu / nist.gov. If a variant is
 * missing we fall back to one we do have rather than shipping a broken ref.
 */
async function writeAssetsModule() {
  const want = {
    cmuLight: "cmu-wordmark.png",
    cmuDark: "cmu-wordmark-white.png",
    nistLight: "nist-logo.svg",
    nistDark: "nist-logo-white.svg",
  };
  const out = {};
  for (const [key, file] of Object.entries(want)) {
    const actual = existsSync(join(ASSETS, file))
      ? file
      : Object.values(want).find((f) => existsSync(join(ASSETS, f)));
    if (!actual) throw new Error(`no logo assets found in ${ASSETS}`);
    out[key] = await dataUri(actual);
  }
  const body =
    "/* AUTO-GENERATED by build.mjs — logo assets inlined as data URIs. */\n\n" +
    "export const ASSETS = {\n" +
    Object.entries(out).map(([k, v]) => `  ${k}: "${v}",`).join("\n") +
    "\n} as const;\n";
  await writeFile(join(SRC, "assets.gen.ts"), body, "utf8");
  const kb = (body.length / 1024).toFixed(1);
  console.log(`  assets.gen.ts     ${kb} KB inlined (${Object.keys(out).length} logos)`);
}

function htmlShell({ css, js, boot, title, description }) {
  return `<!doctype html>
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="color-scheme" content="light dark">
<title>${title}</title>
<meta name="description" content="${description}">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='7' fill='%230f766e'/%3E%3Cpath d='M16 7v18M7 16h18' stroke='white' stroke-width='3.4' stroke-linecap='round'/%3E%3C/svg%3E">
<style>
${css}
</style>
</head>
<body>
<div id="app"></div>
<script id="pt-boot">${boot ? `window.__PT_BOOT__ = ${boot};` : ""}</script>
<script>
${js}
</script>
</body>
</html>
`;
}

async function bundle(entry, minify) {
  const result = await build({
    entryPoints: [join(ROOT, entry)],
    bundle: true,
    format: "iife",
    target: ["es2020", "chrome100", "firefox100", "safari15"],
    platform: "browser",
    minify,
    sourcemap: false,
    legalComments: "none",
    write: false,
    logLevel: "warning",
  });
  return result.outputFiles[0].text;
}

async function main() {
  await mkdir(DIST, { recursive: true });
  console.log("building price-transparency front end");
  await writeAssetsModule();

  const minify = !flag("--no-minify");
  const only = opt("--page", null);
  const outOverride = opt("--out", null);

  let boot = opt("--boot", null);
  const embedDemo = opt("--embed-demo", null);
  if (embedDemo !== null) {
    const scenarios = JSON.parse(await readFile(join(SRC, "demo.json"), "utf8"));
    const payload = scenarios[Number(embedDemo)];
    if (!payload) {
      throw new Error(`--embed-demo ${embedDemo}: only ${scenarios.length} scenarios available`);
    }
    boot = JSON.stringify({ apiBase: "", payload });
    console.log(`  embedding demo scenario ${embedDemo} (${payload.query.slice(0, 46)}…)`);
  }

  const kb = (n) => `${(n / 1024).toFixed(1)} KB`;

  for (const page of PAGES) {
    if (only && page.key !== only) continue;

    const js = await bundle(page.entry, minify);
    const css = await readFile(join(ROOT, page.css), "utf8");
    const html = htmlShell({ css, js, boot, title: page.title, description: page.description });

    const outName = outOverride ? outOverride : page.out;
    await writeFile(join(DIST, outName), html, "utf8");
    console.log(`  dist/${outName.padEnd(18)} ${kb(html.length)}  <- ${page.key}`);
  }

  console.log("done");
}

main().catch((err) => {
  console.error("build failed:", err.message);
  process.exit(1);
});
