/* AUTO-GENERATED by tools/gen_demo.py — do not edit by hand.
 * Offline sample payload: price rows are real rows from the local UPMC MRF
 * snapshot; candidates, decisions, timings and answers are transcribed from
 * the notebook run of Copy_of_Try_PT-3.ipynb. */

import data from "./demo.json";
import type { PipelineResult } from "./types";

export const DEMO_SCENARIOS = data as unknown as PipelineResult[];
